name: PR Notification

on:
  pull_request:
    types: [ opened, reopened, ready_for_review ]

jobs:
  pr-notification:
    name: Notify PE Internal Slack channel about PR
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.ORG_PE_INTERNAL_CHANNEL_WEBHOOK }}
          SLACK_COLOR: 'good'
          SLACK_USERNAME: 'PE GHA Notifications'
          SLACK_MESSAGE: '${{ github.event.pull_request.title }}: ${{ github.event.pull_request.html_url }}'
          SLACK_TITLE: ':bell: Public K8s Resources PR Ready for Review :bell:'